# config.yaml for Hugo + Wowchemy (Modern YAML format)
title: "Gennadii Iakovlev"
baseURL: "https://gennadiiiakovlev.netlify.app/"

############################
# Language Settings
############################
defaultContentLanguage: "en"
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
# Hugo Modules
############################
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy/v5
      version: "latest"
    - path: github.com/wowchemy/wowchemy-hugo-themes/modules/wowchemy-seo
      version: "v0.2.0"

############################
# Advanced Configuration
############################
enableGitInfo: true
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnoteReturnLinkContents: "<sup>^</sup>"
ignoreFiles:
  - "\\.ipynb$"
  - ".ipynb_checkpoints$"
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "_cache$"

permalinks:
  event: "/talk/:slug/"
  tags: "/tag/:slug/"
  categories: "/category/:slug/"
  publication_types: "/publication-type/:slug/"

disableAliases: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
    - headers
    - redirects
  section:
    - HTML
    - RSS

imaging:
  resampleFilter: "lanczos"
  quality: 75
  anchor: "smart"

timeout: 600000

taxonomies:
  tag: "tags"
  category: "categories"
  publication_type: "publication_types"
  author: "authors"

markup:
  _merge: "deep"

related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: "tags"
      weight: 100
    - name: "categories"
      weight: 70

security:
  _merge: "deep"

sitemap:
  changefreq: "weekly"
  priority: 0.8
  title: "News"

############################
# Services (e.g. Analytics)
############################
services:
  googleAnalytics:
    id: "G-B9SJS5JPCS"
