name = "Gennadii Iakovlev"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-academic/blob/master/LICENSE.md"
description = "An academic personal website of Gennadii Iakovlev that feature the most recent publications and databases in political science"
homepage = "https://github.com/wowchemy/starter-hugo-academic/"
demosite = "https://wowchemy.com/templates/"
min_version = "0.84"
tags = ["Gennadii Iakovlev", "Gennadii Iakovlev PhD", "Iakovlev", "pacted transitions"]
features = ["Gennadii Iakovlev", "Gennadii Iakovlev PhD", "Iakovlev", "pacted transitions"]

[author]
  name = "Gennadii Iakovlev"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
